services:
  www:
    image: ghcr.io/felixrizzolli/felixrizzolli-com-www:${WWW_VERSION:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.www.rule=Host(`felixrizzolli.com`) || Host(`www.felixrizzolli.com`)"
      - "traefik.http.routers.www.entrypoints=websecure"
      - "traefik.http.routers.www.tls.certresolver=letsencrypt"
      - "traefik.http.services.www.loadbalancer.server.port=${WWW_PORT}"
    env_file:
      - path: ./.env.prod
        required: true
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://${WWW_HOST}:${WWW_PORT}",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    networks:
      - traefik-public
    depends_on:
      api:
        condition: service_healthy