services:
  docs:
    image: ghcr.io/felixrizzolli/felixrizzolli-com-docs:${DOCS_VERSION:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`docs.felixrizzolli.com`)"
      - "traefik.http.routers.docs.entrypoints=websecure"
      - "traefik.http.routers.docs.tls.certresolver=letsencrypt"
      - "traefik.http.services.docs.loadbalancer.server.port=${DOCS_PORT}"
    env_file:
      - path: ./.env
        required: true
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://${DOCS_HOST}:${DOCS_PORT}",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    networks:
      - felixrizzolli
    depends_on:
      api:
        condition: service_healthy