services:
  traveling:
    container_name: "felixrizzolli-com-traveling"
    image: ghcr.io/felixrizzolli/felixrizzolli-com-traveling:${TRAVELING_VERSION:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traveling.rule=Host(`traveling.felixrizzolli.com`)"
      - "traefik.http.routers.traveling.entrypoints=websecure"
      - "traefik.http.routers.traveling.tls.certresolver=letsencrypt"
      - "traefik.http.services.traveling.loadbalancer.server.port=${TRAVELING_PORT}"
    env_file:
      - path: ./.env.prod
        required: true
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://${TRAVELING_HOST}:${TRAVELING_PORT}",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    networks:
      - traefik-public
    depends_on:
      api:
        condition: service_healthy